name: yob_api
description: YOB K Business API server.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  postgres: ^3.5.5
  dart_jsonwebtoken: ^2.14.1
  bcrypt: ^1.1.3
  dotenv: ^4.2.0
  uuid: ^4.5.1
  yob_core:
    path: ../yob_core

dev_dependencies:
  dart_frog_lint: ^0.1.0
  mocktail: ^1.0.3
  test: ^1.25.5
